# User-defined settings for preparing TraCE-21ka paleoclimate data for LPJ-GUESS
#

# Geographic extent of study area
region:
  # Longitude: 0째 to 360째 E
  lon: [130, 230]
  # Latitude: -90째 to +90째 N
  lat: [50, 80]

# Time frame of interest. In negative thousand calendar years before present (-kaBP).
timeframe: [ -21, -15]
